"""STATUS.md dashboard generator (spec §7).

Auto-generated table, newest first: date · id · approved · status · permalink ·
error. Plus a header block: next scheduled post and (when known) token expiry and
today's publishing quota. Regenerated after render/publish.
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path

from .queue import Post, Status, load_all

MARKER = "<!-- generated by `doxa status`; do not edit by hand -->"


def _row(post: Post) -> str:
    date = post.publish_at.split(" ")[0]
    approved = "✅" if post.approved else "—"
    permalink = f"[link]({post.permalink})" if post.permalink else "—"
    error = (post.error or "—").replace("|", "\\|").replace("\n", " ")
    if len(error) > 80:
        error = error[:77] + "…"
    return f"| {date} | `{post.id}` | {approved} | {post.status.value} | {permalink} | {error} |"


def _next_scheduled(posts: list[Post], now: dt.datetime) -> str:
    upcoming = [
        p for p in posts if p.status in (Status.queued, Status.rendered) and p.publish_at_dt >= now
    ]
    if not upcoming:
        return "none"
    upcoming.sort(key=lambda p: p.publish_at_dt)
    nxt = upcoming[0]
    return f"`{nxt.id}` at {nxt.publish_at} (Asia/Jerusalem)"


def build_status(
    queue_dir: Path,
    now: dt.datetime,
    *,
    token_expiry: str | None = None,
    quota: str | None = None,
) -> str:
    """Render the full STATUS.md content."""
    loaded = load_all(queue_dir)
    posts = [p for _, p in loaded]
    posts_by_date = sorted(posts, key=lambda p: p.publish_at, reverse=True)

    lines: list[str] = []
    lines.append(MARKER)
    lines.append("# DOXA status")
    lines.append("")
    lines.append(f"- **Next scheduled:** {_next_scheduled(posts, now)}")
    lines.append(f"- **Token expiry:** {token_expiry or 'unknown'}")
    lines.append(f"- **Today's quota:** {quota or 'unknown'}")
    lines.append("")
    lines.append("| date | id | approved | status | permalink | error |")
    lines.append("|------|----|----------|--------|-----------|-------|")
    for post in posts_by_date:
        lines.append(_row(post))
    lines.append("")
    return "\n".join(lines)


def write_status(
    repo_root: Path,
    now: dt.datetime,
    *,
    token_expiry: str | None = None,
    quota: str | None = None,
) -> Path:
    content = build_status(repo_root / "queue", now, token_expiry=token_expiry, quota=quota)
    out = repo_root / "STATUS.md"
    out.write_text(content, encoding="utf-8")
    return out
